language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository #Google Play Services
    - extra-android-m2repository #Design Support Library
    - extra-android-support
    - addon-google_apis-google-24

script:
   - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace --info --debug